language: python
python:
  - "3.6"
install:
  - pip install flit 
  - pip install -U pytest pytest-cov python-coveralls
  - flit install -s
script:
  - pytest --doctest-modules -v --cov b2luigi --cov-report term-missing
after_success:
  - coveralls
